### ISSUE TITLE
  installation of package ‘hbgd’ had non-zero exit status

### ISSUE THREAD

**Issue by chinyede** [hafen/hbgd#24]
I am using windows 10 on a 64bit machine. I tried installing on a 32bit windows 7 machine and the installation was successful but on my windows 10 machine it still will not install I get the following error.
 
 
 
options(repos = c(
+   CRAN = "http://cran.rstudio.com/",
+   tessera = "http://packages.tessera.io"))
> install.packages("hbgd")
Installing package into ‘C:/Users/rchiruka/Desktop/rpackages’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository http://packages.tessera.io/bin/windows/contrib/3.5:
  cannot open URL 'http://packages.tessera.io/bin/windows/contrib/3.5/PACKAGES'
installing the source package ‘hbgd’
 
trying URL 'http://packages.tessera.io/src/contrib/hbgd_0.3.8.tar.gz'
Content type 'application/x-gzip' length 172198 bytes (168 KB)
downloaded 168 KB

..........
Error: unknown input format
* removing 'C:/Users/rchiruka/Desktop/rpackages/hbgd'
In R CMD INSTALL
 
The downloaded source packages are in
        ‘C:\Users\rchiruka\AppData\Local\Temp\RtmpMbSM2Y\downloaded_packages’
Warning message:
In install.packages("hbgd") :
  installation of package ‘hbgd’ had non-zero exit status

**Comment by hdoubleu** [comment]
Try to install using the following, as shown at http://hbgdki.github.io/hbgd/

`options(repos = c(
  CRAN = "http://cran.rstudio.com/",
  deltarho = "http://packages.deltarho.org"))
install.packages("hbgd")`

Tested on R v3.5.2 64-bit on 64-bit Windows 10.
Note: the installation can sometime fail due to package dependencies, in these cases, just manually install them. E.g., if the error message states `lme4` is not found, install by issuing `install.packages('lme4')`. Then attempt to reinstall `hbgd` by issuing `install.packages('hbgd')`

**Comment by myrtaar** [comment]
when using 'options(repos = c( CRAN = "http://cran.rstudio.com/", deltarho = "http://packages.deltarho.org"))
install.packages("hbgd")'

I receive error message: Warning in install.packages :
  package ‘hbgd’ is not available (for R version 3.6.0)

Is there an updated version of HBGD for R 3.6.0 or later?

**Comment by hafen** [comment]
I updated the installation instructions in the README. Note that this package is not under active development anymore. If you are using it for the growth standard calculations, please see here: https://ki-tools.github.io/growthstandards/
